// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSIE-EFXpxgLjNhDdvL2QxuUU_2P8YsI',
    appId: '1:241273836703:web:73ee93f76acb34edd8beaa',
    messagingSenderId: '241273836703',
    projectId: 'nutritrack-app-47ac2',
    authDomain: 'nutritrack-app-47ac2.firebaseapp.com',
    storageBucket: 'nutritrack-app-47ac2.firebasestorage.app',
    measurementId: 'G-RX61CSYNN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFZG6VKQxLcZFvVcMXFQV3MVQQLrY8ork',
    appId: '1:241273836703:android:8c66bc39a3691c49d8beaa',
    messagingSenderId: '241273836703',
    projectId: 'nutritrack-app-47ac2',
    storageBucket: 'nutritrack-app-47ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRPf3acNyp7CN5AgEPdWN-U44yaJEDWME',
    appId: '1:241273836703:ios:03551e46c9784144d8beaa',
    messagingSenderId: '241273836703',
    projectId: 'nutritrack-app-47ac2',
    storageBucket: 'nutritrack-app-47ac2.firebasestorage.app',
    iosBundleId: 'com.example.nutritrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRPf3acNyp7CN5AgEPdWN-U44yaJEDWME',
    appId: '1:241273836703:ios:03551e46c9784144d8beaa',
    messagingSenderId: '241273836703',
    projectId: 'nutritrack-app-47ac2',
    storageBucket: 'nutritrack-app-47ac2.firebasestorage.app',
    iosBundleId: 'com.example.nutritrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdSIE-EFXpxgLjNhDdvL2QxuUU_2P8YsI',
    appId: '1:241273836703:web:70792d8320be3be2d8beaa',
    messagingSenderId: '241273836703',
    projectId: 'nutritrack-app-47ac2',
    authDomain: 'nutritrack-app-47ac2.firebaseapp.com',
    storageBucket: 'nutritrack-app-47ac2.firebasestorage.app',
    measurementId: 'G-HBSXZ9PY9Q',
  );
}
